// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIh7DUEk1IWjz3aW7PgLQjFhlZEW9jZIg',
    appId: '1:804312353430:web:5a4054446a35dcd3c1d0b7',
    messagingSenderId: '804312353430',
    projectId: 'plantify-d36ed',
    authDomain: 'plantify-d36ed.firebaseapp.com',
    storageBucket: 'plantify-d36ed.appspot.com',
    measurementId: 'G-GZ0TBCSS23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIBtlAf-isRYN_BpIx5PDuGKk4WFPgXEk',
    appId: '1:804312353430:android:6bd7290a0857c09bc1d0b7',
    messagingSenderId: '804312353430',
    projectId: 'plantify-d36ed',
    storageBucket: 'plantify-d36ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCagCJ6ofEvS5JBsUxSffcgrvtfZ_7R5Ek',
    appId: '1:804312353430:ios:9eeaeb07c09e319ac1d0b7',
    messagingSenderId: '804312353430',
    projectId: 'plantify-d36ed',
    storageBucket: 'plantify-d36ed.appspot.com',
    iosClientId: '804312353430-piup6dag80sfcs8c76sp9ff3n5d7lbua.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCagCJ6ofEvS5JBsUxSffcgrvtfZ_7R5Ek',
    appId: '1:804312353430:ios:9eeaeb07c09e319ac1d0b7',
    messagingSenderId: '804312353430',
    projectId: 'plantify-d36ed',
    storageBucket: 'plantify-d36ed.appspot.com',
    iosClientId: '804312353430-piup6dag80sfcs8c76sp9ff3n5d7lbua.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantify',
  );
}
